version: '3.9'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
    - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$PG_USERNAME"]
      interval: 1s
      timeout: 5s
      retries: 10
  api:
    build: ./backend
    image: backend
    depends_on:
    - "postgres"
    ports:
    - 8080:8080
  # frontend:
  #   build: ./frontend
  #   image: frontend:latest
  #   ports:
  #   - 80:3000
  #   depends_on:
  #   - "api"